name: Test & Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is-new: ${{ steps.is-new-version.outputs.is-new }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Module Version
        id: get-version
        shell: pwsh
        run: |
          Import-Module ./kurukuru-pwsh.psd1
          $version = (Get-Module kurukuru-pwsh).Version.ToString()
          Write-Output $version
          Write-Output "::set-output name=version::$version"

      - name: Check tag
        uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: v${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: is new version?
        id: is-new-version
        run: |
          IS_NEW=false
          if [ "${{ steps.check-tag.outputs.exists }}" = "false" ]; then
            echo "new version tag project: ${{ steps.get-version.outputs.version }}"
            IS_NEW=true
          fi
          echo "::set-output name=is-new::$IS_NEW"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pester
        shell: pwsh
        run: Invoke-Pester ./tests/Start-Kurukuru.Tests.ps1

  new-version-only:
    runs-on: ubuntu-latest
    needs: [get-version, test]
    if: ${{ needs.get-version.outputs.is-new == 'true' }}
    steps:
      - run: echo "new-version"

  publish:
    runs-on: windows-latest
    environment:
      name: actions
      url: https://github.com
    needs: [get-version, new-version-only]
    steps:
      - uses: actions/checkout@v2
      - name: Push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.get-version.outputs.version }}
          tag_prefix: "v"

      - name: Create release
        uses: ncipollo/release-action@v1
        id: create-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag-version.outputs.new_tag }}
          name: Version ${{ needs.get-version.outputs.version }}
          body: https://github.com/${{ github.repository }}/blob/${{ steps.tag-version.outputs.new_tag }}/CHANGELOG.md

      - name: Install-Module PowerShellGet
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PowerShellGet -MinimumVersion "3.0.12-beta" -AllowPrerelease -Repository PSGallery -AllowClobber -Force

      - name: Publish
        shell: pwsh
        run: |
          $NUGET_KEY = "${{ secrets.PWSH_NUGET_KEY  }}"
          tools/dist.ps1 -TagName "v${{ needs.get-version.outputs.version }}"
          Import-Module PowerShellGet
          Publish-PSResource -Path ./kurukuru-pwsh -APIKey "$NUGET_KEY" -Repository PSGallery
